import React, { useMemo } from 'react';
import { Modal, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { IconClose, IconUpload, IconCamera, IconGallery } from './Icons';
import { radii } from '../theme';
import { useModalAccessibilityFocus, useReducedMotion } from '../ui/primitives';

function SourceOption({ title, description, badge, localOnly = false, icon, onPress, palette, styles, accessibilityLabel }) {
  return <TouchableOpacity style={[styles.action, localOnly && styles.actionLocal]} onPress={onPress} accessibilityRole="button" accessibilityLabel={accessibilityLabel} activeOpacity={0.72}><View style={[styles.iconWell, localOnly && styles.iconWellLocal]}>{icon}</View><View style={styles.copy}><View style={styles.titleRow}><Text style={styles.actionTitle}>{title}</Text><View style={[styles.badge, localOnly ? styles.badgeLocal : styles.badgeExternal]}><Text style={[styles.badgeText, localOnly ? styles.badgeTextLocal : styles.badgeTextExternal]}>{badge}</Text></View></View><Text style={styles.actionText}>{description}</Text></View></TouchableOpacity>;
}

export default function AttachmentSourceSheet({ visible, onClose, onDocument, onImage, onApk, onCamera, onGallery, palette, returnFocusRef }) {
  const styles = useMemo(() => createStyles(palette), [palette]);
  const reducedMotion = useReducedMotion();
  const modalTitleRef = useModalAccessibilityFocus(visible, returnFocusRef);
  const choose = async (handler) => { onClose(); await handler(); };
  return <Modal visible={visible} transparent={false} statusBarTranslucent={false} navigationBarTranslucent={false} presentationStyle="fullScreen" animationType={reducedMotion ? 'none' : 'slide'} onRequestClose={onClose}><View style={styles.backdrop}><TouchableOpacity style={StyleSheet.absoluteFill} activeOpacity={1} onPress={onClose} accessibilityRole="button" accessibilityLabel="Close attachment source picker" /><View style={styles.sheet} accessibilityViewIsModal><View style={styles.header}><View style={styles.headerCopy}><Text ref={modalTitleRef} accessible accessibilityRole="header" style={styles.title}>Stage intelligence</Text><Text style={styles.subtitle}>Dr Stones Command Centre keeps device-bound APKs inert and local. You review each external transmission before it reaches the selected AI provider.</Text></View><TouchableOpacity style={styles.close} onPress={onClose} accessibilityRole="button" accessibilityLabel="Close attachment source picker"><IconClose color={palette.textMuted} /></TouchableOpacity></View><ScrollView style={styles.body} contentContainerStyle={styles.bodyContent} showsVerticalScrollIndicator={false}><Text style={styles.sectionLabel}>EXTERNAL COMMAND INPUT</Text><SourceOption title="Source document // PDF / ZIP" badge="Transmit on command" description="Stage local source material. PDF text is inspected on-device where supported." icon={<IconUpload size={19} color={palette.cyanBright} />} onPress={() => choose(onDocument)} palette={palette} styles={styles} accessibilityLabel="Upload a document, PDF or ZIP archive" /><SourceOption title="Visual intelligence" badge="Transmit on command" description="Stage a JPEG, PNG, WebP or GIF up to 8 MB for visual review." icon={<IconGallery size={20} color={palette.cyanBright} />} onPress={() => choose(onImage)} palette={palette} styles={styles} accessibilityLabel="Upload an image file" /><SourceOption title="Live capture" badge="Transmit on command" description="Capture an image now, then confirm before it is used in a request." icon={<IconCamera size={20} color={palette.cyanBright} />} onPress={() => choose(onCamera)} palette={palette} styles={styles} accessibilityLabel="Capture an image with the camera" /><SourceOption title="Device gallery" badge="Transmit on command" description="Select an existing image from your device library." icon={<IconGallery size={20} color={palette.cyanBright} />} onPress={() => choose(onGallery)} palette={palette} styles={styles} accessibilityLabel="Select an image from the device gallery" /><Text style={styles.sectionLabel}>DEVICE-BOUND EVIDENCE</Text><SourceOption title="Android APK" badge="Device-bound" localOnly description="Stage an APK up to 150 MB. It remains inert on-device; only filename and size context can be shared." icon={<IconUpload size={19} color={palette.success || palette.cyanBright} />} onPress={() => choose(onApk)} palette={palette} styles={styles} accessibilityLabel="Upload an Android APK" /></ScrollView></View></View></Modal>;
}

const createStyles = (colors) => StyleSheet.create({ backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: colors.bg }, sheet: { maxHeight: '92%', backgroundColor: colors.bg, borderTopLeftRadius: radii.xl, borderTopRightRadius: radii.xl, borderWidth: 1, borderColor: colors.border }, header: { minHeight: 96, padding: 16, flexDirection: 'row', alignItems: 'flex-start', gap: 12, justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.black, backgroundColor: colors.black }, headerCopy: { flex: 1, minWidth: 0 }, title: { color: '#ffffff', fontSize: 18, fontWeight: '800', letterSpacing: -0.2 }, subtitle: { marginTop: 5, color: '#d4d4d0', fontSize: 11, lineHeight: 16 }, close: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', backgroundColor: '#252523', borderWidth: 1, borderColor: '#5f5f5b', borderRadius: radii.sm }, body: { flexGrow: 0 }, bodyContent: { padding: 16, gap: 10 }, sectionLabel: { marginTop: 2, color: colors.textMuted, fontSize: 10, fontWeight: '800', letterSpacing: 0.8 }, action: { minHeight: 84, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.border, borderRadius: radii.lg }, actionLocal: { borderColor: colors.black, backgroundColor: colors.cyanDim }, iconWell: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: radii.md, backgroundColor: colors.panelAlt, borderWidth: 1, borderColor: colors.border }, iconWellLocal: { borderColor: colors.black, backgroundColor: colors.bg }, copy: { flex: 1, minWidth: 0 }, titleRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 6 }, actionTitle: { color: colors.textSecondary, fontWeight: '800', fontSize: 13 }, actionText: { marginTop: 5, color: colors.textFaint, fontSize: 10, lineHeight: 15 }, badge: { minHeight: 22, paddingHorizontal: 7, alignItems: 'center', justifyContent: 'center', borderRadius: radii.pill, borderWidth: 1 }, badgeExternal: { backgroundColor: colors.panelAlt, borderColor: colors.border }, badgeLocal: { backgroundColor: colors.black, borderColor: colors.black }, badgeText: { fontSize: 9, fontWeight: '800' }, badgeTextExternal: { color: colors.textMuted }, badgeTextLocal: { color: '#ffffff' } });
