import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { IconDocument, IconRedo, IconSearch, IconTrash, IconUndo } from './Icons';
import { AccessibleReorderControls, Button, Chip, DocumentCard, DocumentToolbar, EmptyState, IconButton, SearchField, TextField } from '../ui/primitives';
import { DOCUMENT_TEMPLATES } from '../documents/documentTemplates.mjs';
import { addSection, archiveDocument, compareRevisions, createDocument, createNamedSnapshot, createRevision, deleteSection, duplicateDocument, moveSection, renameDocument, restoreRevisionNonDestructive, searchDocuments, sortDocuments, updateComposition, updateDocumentMeta, updateSection } from '../documents/documentDomain.mjs';

const TYPES=['PARAGRAPH','HEADING','LIST','QUOTE','CODE','PAGE_BREAK'];
export default function DocumentStudio({documents=[],revisions=[],activeDocumentId,workspaceId,onSelectDocument,onChangeDocuments,onChangeRevisions,onDeleteDocument,onPreview,onExport,onExportProject,onImportProject,onAiOperation,documentGeneration,onStopAi,onRetryAi,palette,layout='compact'}){
 const s=useMemo(()=>styles(palette),[palette]); const [query,setQuery]=useState(''); const [sort,setSort]=useState('updated'); const [showArchived,setShowArchived]=useState(false); const [find,setFind]=useState(''); const [history,setHistory]=useState([]); const [future,setFuture]=useState([]); const [compare,setCompare]=useState(null); const [aiTargetSectionId,setAiTargetSectionId]=useState(null); const editorScrollRef=useRef(null); const sectionY=useRef(new Map());
 const active=documents.find(d=>d.id===activeDocumentId)||documents.find(d=>d.workspaceId===workspaceId&&d.status!=='ARCHIVED')||null;
 const scoped=sortDocuments(searchDocuments(documents.filter(d=>d.workspaceId===workspaceId&&(showArchived?d.status==='ARCHIVED':d.status!=='ARCHIVED')),query),sort);
 useEffect(()=>{setHistory([]);setFuture([]);setCompare(null);setAiTargetSectionId(active?.sections?.[0]?.id||null);},[active?.id]);
 const commit=(next)=>{if(!active)return;setHistory(h=>[...h,active].slice(-30));setFuture([]);onChangeDocuments(documents.map(d=>d.id===active.id?next:d));};
 const create=(template)=>{const d=createDocument({workspaceId,template,title:template?.name||'Untitled Document'});onChangeDocuments([...documents,d]);onSelectDocument(d.id);setShowArchived(false);};
 const undo=()=>{if(!active||!history.length)return;const previous=history.at(-1);if(previous.id!==active.id){setHistory([]);setFuture([]);return;}setHistory(h=>h.slice(0,-1));setFuture(f=>[active,...f].slice(0,30));onChangeDocuments(documents.map(d=>d.id===active.id?previous:d));};
 const redo=()=>{if(!active||!future.length)return;const next=future[0];if(next.id!==active.id){setHistory([]);setFuture([]);return;}setFuture(f=>f.slice(1));setHistory(h=>[...h,active].slice(-30));onChangeDocuments(documents.map(d=>d.id===active.id?next:d));};
 const snapshot=()=>{if(!active)return;const result=createNamedSnapshot(active,revisions,`Snapshot ${new Date().toLocaleString()}`);onChangeDocuments(documents.map(d=>d.id===active.id?result.document:d));onChangeRevisions(result.revisions);};
 const latest=useMemo(()=>revisions.filter(r=>r.documentId===active?.id).sort((a,b)=>b.createdAt-a.createdAt),[revisions,active?.id]);
 const restore=(id)=>{const out=restoreRevisionNonDestructive(active,revisions,id);onChangeDocuments(documents.map(d=>d.id===active.id?out.document:d));onChangeRevisions(out.revisions);};
 const doCompare=()=>{if(latest.length<2)return;setCompare(compareRevisions(latest[1],latest[0]));};
 const goHeading=(section)=>{const y=sectionY.current.get(section.id); if(Number.isFinite(y)) editorScrollRef.current?.scrollTo?.({y:Math.max(0,y-12),animated:true});};
 const confirmDelete=()=>{if(!active||!onDeleteDocument)return;Alert.alert('Delete document?',`Delete “${active.title}” and its revision history?`,[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>onDeleteDocument(active.id)}]);};
 const browser=<ScrollView style={[s.browser,layout==='compact'&&s.browserCompact]} contentContainerStyle={s.browserBody} keyboardShouldPersistTaps="handled" nestedScrollEnabled><SearchField value={query} onChangeText={setQuery} placeholder={showArchived?'Search archived documents':'Search documents'} palette={palette}/><View style={s.row}><Chip label="Recent" selected={!showArchived&&sort==='updated'} onPress={()=>{setShowArchived(false);setSort('updated');}} palette={palette}/><Chip label="A–Z" selected={!showArchived&&sort==='title'} onPress={()=>{setShowArchived(false);setSort('title');}} palette={palette}/><Chip label="Archived" selected={showArchived} onPress={()=>setShowArchived(v=>!v)} palette={palette}/></View><View style={s.documentList}>{scoped.map(doc=><DocumentCard key={doc.id} document={doc} selected={doc.id===active?.id} onPress={()=>onSelectDocument(doc.id)} palette={palette}/>)}</View>{!showArchived&&<><Text style={s.sectionLabel}>Templates</Text><View style={s.wrap}>{DOCUMENT_TEMPLATES.map(t=><Chip key={t.id||t.name} label={t.name} onPress={()=>create(t)} palette={palette}/>)}</View><Button label="New blank document" onPress={()=>create(null)} palette={palette} kind="primary"/></>}<Button label="Import document project ZIP" onPress={onImportProject} palette={palette}/></ScrollView>;
 if(!active)return <View style={s.root}>{browser}<EmptyState title={showArchived?'No archived documents':'Document Studio'} detail={showArchived?'Archived documents will appear here and can be opened and restored.':'Create reports, specifications, audits, implementation plans, memoranda, proposals and formal letters locally.'} actionLabel={showArchived?undefined:'Create document'} onAction={()=>create(null)} icon={<IconDocument size={36} color={palette.cyanBright}/>} palette={palette}/></View>;
 const editor=<View style={s.editor}><DocumentToolbar palette={palette}><IconButton label="Undo" onPress={undo} disabled={!history.length} palette={palette}><IconUndo color={palette.textMuted}/></IconButton><IconButton label="Redo" onPress={redo} disabled={!future.length} palette={palette}><IconRedo color={palette.textMuted}/></IconButton><View style={s.find}><IconSearch size={16} color={palette.textMuted}/><TextInput value={find} onChangeText={setFind} placeholder="Find" placeholderTextColor={palette.textFaint} style={s.findInput} accessibilityLabel="Find in document"/></View></DocumentToolbar><ScrollView ref={editorScrollRef} contentContainerStyle={s.editorBody} keyboardShouldPersistTaps="handled">
  <Text accessibilityLiveRegion="polite" style={s.status}>Save status: {active.autosaveStatus}</Text>
  <TextField label="Title" value={active.title} onChangeText={v=>commit(renameDocument(active,v))} palette={palette}/><View style={s.row}><View style={{flex:1}}><TextField label="Subtitle" value={active.subtitle} onChangeText={v=>commit(updateDocumentMeta(active,{subtitle:v}))} palette={palette}/></View><View style={{flex:1}}><TextField label="Author" value={active.author} onChangeText={v=>commit(updateDocumentMeta(active,{author:v}))} palette={palette}/></View></View>
  <View style={s.row}><Chip label={active.composition.pageSize} onPress={()=>commit(updateComposition(active,{pageSize:active.composition.pageSize==='A4'?'LETTER':'A4'}))} palette={palette}/><Chip label={active.composition.orientation} onPress={()=>commit(updateComposition(active,{orientation:active.composition.orientation==='portrait'?'landscape':'portrait'}))} palette={palette}/><Chip label="Cover" selected={active.composition.coverPage} onPress={()=>commit(updateComposition(active,{coverPage:!active.composition.coverPage}))} palette={palette}/><Chip label="TOC" selected={active.composition.tableOfContents} onPress={()=>commit(updateComposition(active,{tableOfContents:!active.composition.tableOfContents}))} palette={palette}/><Chip label="Page nos" selected={active.composition.pageNumbers} onPress={()=>commit(updateComposition(active,{pageNumbers:!active.composition.pageNumbers}))} palette={palette}/></View>
  <View style={s.row}><Chip label="Standard margins" onPress={()=>commit(updateComposition(active,{margins:{top:20,right:20,bottom:20,left:20}}))} palette={palette}/><Chip label="Narrow" onPress={()=>commit(updateComposition(active,{margins:{top:12,right:12,bottom:12,left:12}}))} palette={palette}/><Chip label="Wide" onPress={()=>commit(updateComposition(active,{margins:{top:28,right:28,bottom:28,left:28}}))} palette={palette}/></View>
  <TextField label="Header" value={active.composition.header} onChangeText={v=>commit(updateComposition(active,{header:v}))} palette={palette}/><TextField label="Footer" value={active.composition.footer} onChangeText={v=>commit(updateComposition(active,{footer:v}))} palette={palette}/>
  <Text style={s.sectionLabel}>Outline</Text><ScrollView horizontal>{active.sections.filter(x=>x.type==='HEADING').map(x=><Chip key={x.id} label={x.content||`Heading ${x.headingLevel}`} accessibilityLabel={`Heading level ${x.headingLevel}: ${x.content||'Untitled heading'}`} accessibilityHint="Move editor to this heading" onPress={()=>goHeading(x)} palette={palette}/>)}</ScrollView>
  {active.sections.map((section,index)=><View key={section.id} onLayout={e=>sectionY.current.set(section.id,e.nativeEvent.layout.y)} style={[s.section,find&&section.content.toLowerCase().includes(find.toLowerCase())&&s.match]}><View style={s.sectionHead}><TouchableOpacity onPress={()=>commit(updateSection(active,section.id,{type:TYPES[(TYPES.indexOf(section.type)+1)%TYPES.length]}))} style={s.typeBtn} accessibilityRole="button" accessibilityLabel={`Change section type from ${section.type}`}><Text style={s.typeText}>{section.type}{section.type==='HEADING'?` H${section.headingLevel}`:''}</Text></TouchableOpacity>{section.type==='HEADING'&&<TouchableOpacity style={s.typeBtn} onPress={()=>commit(updateSection(active,section.id,{headingLevel:(section.headingLevel%3)+1}))} accessibilityRole="button" accessibilityLabel="Change heading level"><Text style={s.typeText}>H{section.headingLevel}</Text></TouchableOpacity>}<AccessibleReorderControls label={`section ${index+1}`} onUp={()=>commit(moveSection(active,section.id,'up'))} onDown={()=>commit(moveSection(active,section.id,'down'))} disableUp={index===0} disableDown={index===active.sections.length-1} palette={palette}/><IconButton label={`Delete section ${index+1}`} onPress={()=>commit(deleteSection(active,section.id))} palette={palette}><IconTrash color={palette.rose}/></IconButton></View>{section.type==='PAGE_BREAK'?<Text style={s.pageBreak}>— Page break —</Text>:<TextInput value={section.content} onChangeText={v=>commit(updateSection(active,section.id,{content:v}))} multiline style={[s.sectionInput,section.type==='CODE'&&s.code]} placeholder={`Write ${section.type.toLowerCase()}…`} placeholderTextColor={palette.textFaint} accessibilityLabel={`Section ${index+1} ${section.type}`}/>}</View>)}
  <Text style={s.sectionLabel}>Add section</Text><View style={s.wrap}>{TYPES.map(type=><Chip key={type} label={type.replace('_',' ')} onPress={()=>commit(addSection(active,{type}))} palette={palette}/>)}</View>
  <Text style={s.sectionLabel}>Revisions</Text><View style={s.wrap}><Button label="Create snapshot" onPress={snapshot} palette={palette}/><Button label="Compare latest" onPress={doCompare} disabled={latest.length<2} palette={palette}/></View>{compare&&<View style={s.compareBox}><Text style={s.comparison}>Title changed: {String(compare.titleChanged)} · Sections {compare.sectionCountBefore} → {compare.sectionCountAfter} · Changed sections: {compare.changedSections}</Text>{(compare.changes||[]).slice(0,12).map((change,index)=><Text key={`${change.sectionId||index}-${index}`} style={s.compareLine}>{change.summary || `${change.kind}: ${change.before || '∅'} → ${change.after || '∅'}`}</Text>)}</View>}{latest.slice(0,8).map(r=><View key={r.id} style={s.revision}><Text style={s.revisionText}>{r.label} · {r.kind}</Text><Button label="Restore non-destructively" onPress={()=>restore(r.id)} palette={palette}/></View>)}
  <Text style={s.sectionLabel}>AI document operations</Text><Text style={s.status}>Insert and replace require an explicit target section.</Text>{documentGeneration?.documentId===active.id&&<View style={s.aiStatus} accessibilityLiveRegion="polite"><Text style={s.status}>Generation: {documentGeneration.status}{documentGeneration.receivedCharacters?` · ${documentGeneration.receivedCharacters} characters`:''}</Text>{documentGeneration.error&&<Text style={s.aiError}>{documentGeneration.error}</Text>}<View style={s.row}>{documentGeneration.status==='STREAMING'&&<Button label="Stop AI operation" onPress={onStopAi} palette={palette}/>} {['FAILED','CANCELLED'].includes(documentGeneration.status)&&<Button label="Retry AI operation" onPress={onRetryAi} palette={palette}/>}</View></View>}<ScrollView horizontal>{active.sections.map((section,index)=><Chip key={section.id} label={`Section ${index+1}`} selected={aiTargetSectionId===section.id} onPress={()=>setAiTargetSectionId(section.id)} palette={palette}/>)}</ScrollView><View style={s.wrap}><Button label="AI append" onPress={()=>onAiOperation?.('append',active,null)} disabled={documentGeneration?.status==='STREAMING'} palette={palette}/><Button label="AI insert" onPress={()=>onAiOperation?.('insert',active,aiTargetSectionId)} disabled={!aiTargetSectionId||documentGeneration?.status==='STREAMING'} palette={palette}/><Button label="AI replace" onPress={()=>onAiOperation?.('replace',active,aiTargetSectionId)} disabled={!aiTargetSectionId||documentGeneration?.status==='STREAMING'} palette={palette}/></View>
  <Text style={s.sectionLabel}>Preview & export</Text><View style={s.wrap}><Button label="Preview PDF" onPress={()=>onPreview(active)} palette={palette}/>{['pdf','md','txt','html'].map(f=><Button key={f} label={`Export ${f.toUpperCase()}`} onPress={()=>onExport(active,f)} palette={palette}/>)}</View><Text style={s.partial}>DOCX: PARTIAL — not claimed as a fidelity-safe export in this release.</Text><Button label="Export safe document-project ZIP" onPress={()=>onExportProject(active)} palette={palette}/><View style={s.row}><Button label="Duplicate document" onPress={()=>{const d=duplicateDocument(active);onChangeDocuments([...documents,d]);onSelectDocument(d.id);}} palette={palette}/><Button label={active.status==='ARCHIVED'?'Unarchive':'Archive'} onPress={()=>commit(archiveDocument(active,active.status!=='ARCHIVED'))} palette={palette}/><Button label="Delete document" onPress={confirmDelete} palette={palette}/></View>
 </ScrollView></View>;
 return <View style={[s.root,layout!=='compact'&&s.wide]}>{layout==='expanded'?<><View style={s.leftPane}>{browser}</View><View style={s.middlePane}>{editor}</View><ScrollView style={s.rightPane} contentContainerStyle={s.rightPaneBody}><Text style={s.sectionLabel}>Outline & properties</Text><Text accessibilityLiveRegion="polite" style={s.status}>Save: {active.autosaveStatus}</Text><Text style={s.status}>Template: {active.templateId || 'blank'}</Text><Text style={s.status}>Type: {active.documentType || 'document'}</Text><Text style={s.status}>Page: {active.composition.pageSize} · {active.composition.orientation}</Text><Text style={s.status}>Margins: {active.composition.margins.top}/{active.composition.margins.right}/{active.composition.margins.bottom}/{active.composition.margins.left}</Text><Text style={s.sectionLabel}>Headings</Text>{active.sections.filter(x=>x.type==='HEADING').map((x,index)=><TouchableOpacity key={x.id} style={s.outlineRow} onPress={()=>goHeading(x)} accessibilityRole="button" accessibilityLabel={`Go to heading ${index+1}: ${x.content||'Untitled'}`}><Text style={s.outlineText}>{'  '.repeat(Math.max(0,(x.headingLevel||1)-1))}{x.content||`Heading ${index+1}`}</Text></TouchableOpacity>)}<Text style={s.sectionLabel}>History</Text><Text style={s.status}>{latest.length} revisions · {(active.snapshotIds||[]).length} named snapshots</Text></ScrollView></>:layout==='medium'?<><View style={s.leftPaneMedium}>{browser}</View><View style={s.middlePane}>{editor}</View></>:<>{browser}{editor}</>}</View>;
}
const styles=(c)=>StyleSheet.create({root:{flex:1,minHeight:0,backgroundColor:c.bg},wide:{flexDirection:'row'},browser:{maxHeight:300,flexShrink:1,minHeight:0,borderBottomWidth:1,borderBottomColor:c.border},browserBody:{padding:10,gap:8},browserCompact:{maxHeight:248},documentList:{maxHeight:168},leftPane:{width:310,borderRightWidth:1,borderRightColor:c.border},middlePane:{flex:1,minWidth:0},rightPane:{width:260,borderLeftWidth:1,borderLeftColor:c.border},rightPaneBody:{padding:14,gap:7},leftPaneMedium:{width:280,borderRightWidth:1,borderRightColor:c.border},outlineRow:{minHeight:48,justifyContent:'center',borderBottomWidth:1,borderBottomColor:c.border},outlineText:{color:c.textSecondary,fontSize:11},editor:{flex:1,minHeight:0},editorBody:{padding:14,gap:12,paddingBottom:116},row:{flexDirection:'row',gap:8,flexWrap:'wrap'},wrap:{flexDirection:'row',gap:8,flexWrap:'wrap'},find:{flex:1,minWidth:120,flexDirection:'row',alignItems:'center',gap:6},findInput:{flex:1,minHeight:48,color:c.textPrimary},sectionLabel:{color:c.cyanBright,fontSize:11,fontWeight:'800',textTransform:'uppercase',letterSpacing:1,marginTop:8},section:{borderWidth:1,borderColor:c.border,borderRadius:12,backgroundColor:c.surfaceElevated,overflow:'hidden'},match:{borderColor:c.cyanBright},sectionHead:{minHeight:48,flexDirection:'row',alignItems:'center',paddingLeft:8,borderBottomWidth:1,borderBottomColor:c.border},typeBtn:{minHeight:48,justifyContent:'center',paddingHorizontal:8},typeText:{color:c.textMuted,fontSize:10,fontWeight:'800'},sectionInput:{minHeight:90,padding:12,color:c.textPrimary,fontSize:14,textAlignVertical:'top'},code:{fontFamily:'monospace'},pageBreak:{padding:18,textAlign:'center',color:c.textFaint},comparison:{color:c.textSecondary,fontSize:12,lineHeight:18},compareBox:{gap:5,padding:10,borderWidth:1,borderColor:c.border,borderRadius:10,backgroundColor:c.panelAlt},compareLine:{color:c.textMuted,fontSize:11,lineHeight:17},aiStatus:{gap:7,padding:10,borderWidth:1,borderColor:c.cyanBorder,borderRadius:10,backgroundColor:c.cyanDim},aiError:{color:c.rose,fontSize:11,lineHeight:16},revision:{minHeight:58,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8,borderBottomWidth:1,borderBottomColor:c.border},revisionText:{flex:1,color:c.textMuted,fontSize:11},partial:{padding:10,color:c.textMuted,fontSize:11,backgroundColor:c.panelAlt,borderRadius:8},status:{color:c.textMuted,fontSize:12,lineHeight:20}});
