import React, { useMemo } from 'react';
import { Modal, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { IconClose } from './Icons';
import { radii } from '../theme';
import { useModalAccessibilityFocus, useReducedMotion } from '../ui/primitives';

export default function PdfReviewSheet({ visible, job, selectedPages = [], onTogglePage, onUse, onCancel, palette, returnFocusRef }) {
  const styles = useMemo(() => createStyles(palette), [palette]);
  const reducedMotion = useReducedMotion();
  const modalTitleRef = useModalAccessibilityFocus(visible, returnFocusRef);
  const selected = new Set(selectedPages);
  if (!job) return null;
  return <Modal visible={visible} transparent={false} statusBarTranslucent={false} navigationBarTranslucent={false} presentationStyle="fullScreen" animationType={reducedMotion ? 'none' : 'slide'} onRequestClose={onCancel}><View style={styles.backdrop}><View style={styles.sheet} accessibilityViewIsModal><View style={styles.header}><View><Text ref={modalTitleRef} accessible accessibilityRole="header" style={styles.title}>PDF page review</Text><Text style={styles.subtitle}>{job.file?.name} · {job.pageCount || 0} page(s)</Text></View><TouchableOpacity style={styles.close} onPress={onCancel} accessibilityRole="button" accessibilityLabel="Cancel PDF review"><IconClose color={palette.textMuted} /></TouchableOpacity></View><ScrollView contentContainerStyle={styles.body}><Text style={styles.note}>Select the pages whose locally extracted text should be placed into transient request context. Image-only pages may contain no extractable text; OCR is never fabricated.</Text>{(job.pages || []).map((page) => <TouchableOpacity key={page.pageNumber} style={[styles.page, selected.has(page.pageNumber) && styles.pageSelected]} onPress={() => onTogglePage(page.pageNumber)} accessibilityRole="checkbox" accessibilityState={{ checked: selected.has(page.pageNumber) }}><View style={styles.pageHeader}><Text style={styles.pageTitle}>Page {page.pageNumber}</Text><Text style={styles.pageState}>{selected.has(page.pageNumber) ? 'Included' : 'Excluded'}</Text></View><Text style={styles.preview} numberOfLines={4}>{page.text?.trim() || 'No extractable text detected on this page.'}</Text></TouchableOpacity>)}</ScrollView><View style={styles.footer}><TouchableOpacity style={styles.secondary} onPress={onCancel} accessibilityRole="button"><Text style={styles.secondaryText}>Cancel</Text></TouchableOpacity><TouchableOpacity style={[styles.primary, !selectedPages.length && styles.disabled]} onPress={onUse} disabled={!selectedPages.length} accessibilityRole="button"><Text style={styles.primaryText}>Use selected pages</Text></TouchableOpacity></View></View></View></Modal>;
}
const createStyles = (colors) => StyleSheet.create({ backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: colors.bg }, sheet: { minHeight: '72%', maxHeight: '95%', backgroundColor: colors.bg, borderTopLeftRadius: radii.xl, borderTopRightRadius: radii.xl, borderWidth: 1, borderColor: colors.border }, header: { padding: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.border }, title: { color: colors.textPrimary, fontSize: 16, fontWeight: '800' }, subtitle: { color: colors.cyanBright, fontSize: 10, marginTop: 3 }, close: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', borderRadius: radii.sm, backgroundColor: colors.panel }, body: { padding: 16, gap: 8 }, note: { color: colors.textFaint, fontSize: 10, lineHeight: 15, marginBottom: 4 }, page: { minHeight: 82, padding: 12, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md }, pageSelected: { borderColor: colors.cyan, backgroundColor: colors.cyanDim }, pageHeader: { flexDirection: 'row', justifyContent: 'space-between' }, pageTitle: { color: colors.textSecondary, fontWeight: '800', fontSize: 12 }, pageState: { color: colors.cyanBright, fontSize: 10, fontWeight: '700' }, preview: { marginTop: 6, color: colors.textMuted, fontSize: 10, lineHeight: 14 }, footer: { padding: 16, flexDirection: 'row', gap: 10, borderTopWidth: 1, borderTopColor: colors.border }, secondary: { flex: 1, minHeight: 48, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: radii.md }, secondaryText: { color: colors.textSecondary, fontWeight: '700' }, primary: { flex: 1.4, minHeight: 48, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.cyan, borderRadius: radii.md }, primaryText: { color: '#fff', fontWeight: '800' }, disabled: { opacity: 0.45 } });
