import React, { useMemo } from 'react';
import { Modal, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { IconClose, IconMic } from './Icons';
import { radii } from '../theme';
import { useModalAccessibilityFocus, useReducedMotion } from '../ui/primitives';

export default function VoiceReviewSheet({ visible, transcript, onChangeTranscript, onAccept, onRetry, onCancel, palette, returnFocusRef }) {
  const styles = useMemo(() => createStyles(palette), [palette]);
  const reducedMotion = useReducedMotion();
  const modalTitleRef = useModalAccessibilityFocus(visible, returnFocusRef);
  return <Modal visible={visible} transparent={false} statusBarTranslucent={false} navigationBarTranslucent={false} presentationStyle="fullScreen" animationType={reducedMotion ? 'none' : 'slide'} onRequestClose={onCancel}><View style={styles.backdrop}><View style={styles.sheet} accessibilityViewIsModal><View style={styles.header}><View><Text ref={modalTitleRef} accessible accessibilityRole="header" style={styles.title}>Review transcript</Text><Text style={styles.subtitle}>Nothing is sent until you accept it.</Text></View><TouchableOpacity style={styles.close} onPress={onCancel} accessibilityRole="button" accessibilityLabel="Discard voice transcript"><IconClose color={palette.textMuted} /></TouchableOpacity></View><View style={styles.body}><TextInput value={transcript} onChangeText={onChangeTranscript} multiline style={styles.input} placeholder="Transcript" placeholderTextColor={palette.textFaint} accessibilityLabel="Voice transcript review" /><View style={styles.actions}><TouchableOpacity style={styles.secondary} onPress={onRetry} accessibilityRole="button"><IconMic size={17} color={palette.cyanBright} /><Text style={styles.secondaryText}>Retry</Text></TouchableOpacity><TouchableOpacity style={styles.primary} onPress={onAccept} accessibilityRole="button"><Text style={styles.primaryText}>Use transcript</Text></TouchableOpacity></View></View></View></View></Modal>;
}
const createStyles = (colors) => StyleSheet.create({ backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: colors.bg }, sheet: { backgroundColor: colors.bg, borderTopLeftRadius: radii.xl, borderTopRightRadius: radii.xl, borderWidth: 1, borderColor: colors.border }, header: { padding: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.border }, title: { color: colors.textPrimary, fontSize: 16, fontWeight: '800' }, subtitle: { marginTop: 3, color: colors.cyanBright, fontSize: 10 }, close: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.panel, borderRadius: radii.sm }, body: { padding: 16, gap: 12 }, input: { minHeight: 120, maxHeight: 240, textAlignVertical: 'top', padding: 12, color: colors.textPrimary, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md }, actions: { flexDirection: 'row', gap: 10 }, secondary: { flex: 1, minHeight: 48, flexDirection: 'row', gap: 7, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.cyanBorder, borderRadius: radii.md }, secondaryText: { color: colors.cyanBright, fontWeight: '800', fontSize: 11 }, primary: { flex: 1.4, minHeight: 48, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.cyan, borderRadius: radii.md }, primaryText: { color: '#fff', fontWeight: '800', fontSize: 11 } });
