import React, { useMemo, useState } from 'react';
import { Alert, Modal, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { IconClose, IconPlus, IconTrash } from './Icons';
import { radii } from '../theme';
import { useModalAccessibilityFocus, useReducedMotion } from '../ui/primitives';

export default function WorkspaceManager({ visible, onClose, workspaces = [], activeWorkspaceId, onCreate, onSelect, onRename, onArchive, onDelete, onAddNote, onExport = () => {}, onImport = () => {}, palette, returnFocusRef }) {
  const styles = useMemo(() => createStyles(palette), [palette]);
  const reducedMotion = useReducedMotion();
  const modalTitleRef = useModalAccessibilityFocus(visible, returnFocusRef);
  const [newName, setNewName] = useState('');
  const [note, setNote] = useState('');
  const [renameId, setRenameId] = useState(null);
  const [renameValue, setRenameValue] = useState('');
  const active = workspaces.find((workspace) => workspace.id === activeWorkspaceId);
  const remove = (workspace) => Alert.alert('Delete workspace?', `Chats will move to another workspace. Delete “${workspace.name}”?`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => onDelete(workspace.id) }]);
  return <Modal visible={visible} transparent={false} statusBarTranslucent={false} navigationBarTranslucent={false} presentationStyle="fullScreen" animationType={reducedMotion ? 'none' : 'slide'} onRequestClose={onClose}><View style={styles.backdrop}><TouchableOpacity style={StyleSheet.absoluteFill} onPress={onClose} activeOpacity={1} accessibilityRole="button" accessibilityLabel="Close workspace manager" /><View style={styles.sheet} accessibilityViewIsModal><View style={styles.header}><Text ref={modalTitleRef} accessible accessibilityRole="header" style={styles.title}>Projects & Workspaces</Text><TouchableOpacity style={styles.close} onPress={onClose} accessibilityRole="button" accessibilityLabel="Close workspace manager"><IconClose color={palette.textMuted} /></TouchableOpacity></View><ScrollView contentContainerStyle={styles.body} keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag">
    <View style={styles.importRow}><TouchableOpacity style={styles.importButton} onPress={onImport} accessibilityRole="button"><Text style={styles.importText}>Import project archive</Text></TouchableOpacity></View>
    <View style={styles.createRow}><TextInput value={newName} onChangeText={setNewName} placeholder="New workspace name" placeholderTextColor={palette.textFaint} style={styles.input} accessibilityLabel="New workspace name" /><TouchableOpacity style={styles.add} onPress={() => { if (newName.trim()) { onCreate(newName.trim()); setNewName(''); } }} accessibilityRole="button" accessibilityLabel="Create workspace"><IconPlus color="#ffffff" /></TouchableOpacity></View>
    {workspaces.map((workspace) => <View key={workspace.id} style={[styles.workspace, workspace.id === activeWorkspaceId && styles.active, workspace.archived && styles.archived]}><TouchableOpacity style={styles.workspaceMain} onPress={() => { onSelect(workspace.id); onClose(); }} accessibilityRole="button"><Text style={styles.workspaceName}>{workspace.name}</Text><Text style={styles.workspaceMeta}>{workspace.chatIds?.length || 0} chats · {workspace.notes?.length || 0} notes{workspace.archived ? ' · archived' : ''}</Text></TouchableOpacity><TouchableOpacity style={styles.small} onPress={() => { setRenameId(workspace.id); setRenameValue(workspace.name); }} accessibilityRole="button"><Text style={styles.smallText}>Rename</Text></TouchableOpacity><TouchableOpacity style={styles.small} onPress={() => onExport(workspace.id)} accessibilityRole="button"><Text style={styles.smallText}>Export</Text></TouchableOpacity><TouchableOpacity style={styles.small} onPress={() => onArchive(workspace.id, !workspace.archived)} accessibilityRole="button" accessibilityLabel={workspace.archived ? 'Unarchive workspace' : 'Archive workspace'}><Text style={styles.smallText}>{workspace.archived ? 'Restore' : 'Archive'}</Text></TouchableOpacity><TouchableOpacity style={styles.small} onPress={() => remove(workspace)} accessibilityRole="button" accessibilityLabel="Delete workspace"><IconTrash size={15} color={palette.rose} /></TouchableOpacity></View>)}
    {renameId && <View style={styles.renamePanel}><Text style={styles.noteTitle}>Rename workspace</Text><TextInput value={renameValue} onChangeText={setRenameValue} style={styles.input} accessibilityLabel="Workspace name" /><View style={styles.renameActions}><TouchableOpacity style={styles.noteButton} onPress={() => { if (renameValue.trim()) onRename(renameId, renameValue.trim()); setRenameId(null); setRenameValue(''); }} accessibilityRole="button"><Text style={styles.noteButtonText}>Save name</Text></TouchableOpacity><TouchableOpacity style={styles.noteButton} onPress={() => { setRenameId(null); setRenameValue(''); }} accessibilityRole="button"><Text style={styles.noteButtonText}>Cancel</Text></TouchableOpacity></View></View>}
    {active && <View style={styles.notePanel}><Text style={styles.noteTitle}>Workspace notes</Text><TextInput value={note} onChangeText={setNote} placeholder="Add an ordinary workspace note" placeholderTextColor={palette.textFaint} style={[styles.input, styles.noteInput]} multiline accessibilityLabel="Workspace note" /><TouchableOpacity style={styles.noteButton} onPress={() => { if (note.trim()) { onAddNote(active.id, note.trim()); setNote(''); } }} accessibilityRole="button"><Text style={styles.noteButtonText}>Add note to {active.name}</Text></TouchableOpacity></View>}
  </ScrollView></View></View></Modal>;
}
const createStyles = (colors) => StyleSheet.create({ backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: colors.bg }, sheet: { minHeight: '60%', maxHeight: '90%', backgroundColor: colors.bg, borderTopLeftRadius: radii.xl, borderTopRightRadius: radii.xl, borderWidth: 1, borderColor: colors.border }, header: { padding: 16, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: colors.border }, title: { color: colors.textPrimary, fontWeight: '700', fontSize: 16 }, close: { height: 48, width: 48, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.panel, borderRadius: radii.sm }, body: { padding: 16, gap: 8 }, importRow: { flexDirection: 'row' }, importButton: { minHeight: 48, flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.cyanDim, borderWidth: 1, borderColor: colors.cyanBorder, borderRadius: radii.md }, importText: { color: colors.cyanBright, fontSize: 11, fontWeight: '800' }, createRow: { flexDirection: 'row', gap: 6 }, input: { flex: 1, minHeight: 48, paddingHorizontal: 12, color: colors.textPrimary, backgroundColor: colors.panel, borderColor: colors.border, borderWidth: 1, borderRadius: radii.md }, add: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.cyan, borderRadius: radii.md }, workspace: { minHeight: 68, flexDirection: 'row', alignItems: 'center', padding: 8, gap: 2, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md }, active: { borderColor: colors.cyan, backgroundColor: colors.cyanDim }, archived: { opacity: 0.6 }, workspaceMain: { flex: 1, minHeight: 48, justifyContent: 'center' }, workspaceName: { color: colors.textSecondary, fontSize: 13, fontWeight: '700' }, workspaceMeta: { marginTop: 3, color: colors.textFaint, fontSize: 10 }, small: { minWidth: 48, minHeight: 48, paddingHorizontal: 4, alignItems: 'center', justifyContent: 'center' }, smallText: { color: colors.cyanBright, fontSize: 9, fontWeight: '700' }, notePanel: { marginTop: 8, padding: 10, gap: 7, backgroundColor: colors.panelAlt, borderRadius: radii.md }, renamePanel: { marginTop: 8, padding: 10, gap: 7, backgroundColor: colors.panelAlt, borderRadius: radii.md }, renameActions: { flexDirection: 'row', gap: 8 }, noteTitle: { color: colors.cyanBright, fontWeight: '700', fontSize: 12 }, noteInput: { minHeight: 72, textAlignVertical: 'top' }, noteButton: { flex: 1, minHeight: 48, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.cyanDim, borderRadius: radii.sm }, noteButtonText: { color: colors.cyanBright, fontWeight: '700', fontSize: 10 } });
