import AsyncStorage from '@react-native-async-storage/async-storage';
import * as SecureStore from 'expo-secure-store';
import { createPinVerifierAsync } from './pinVerifier.mjs';
import { normaliseCState, serialiseCState } from '../workspaces/workspaceSchema.mjs';

const SECURE_KEY_NAME='openRouterKey'; const SECURE_TOGETHER_KEY_NAME='togetherApiKey'; const SECURE_LLM_SETTINGS_PIN='llmSettingsPin';
export const VERSIONED_APP_STATE_KEY='aiConsoleVersionedState'; export const VERSIONED_APP_STATE_BACKUP_KEY='aiConsoleVersionedState.previous';
let stateWriteChain=Promise.resolve(); let secureWriteChain=Promise.resolve();
const serialiseExact=(state)=>JSON.stringify(serialiseCState(state));
export async function getApiKeyResult(){try{return{ok:true,value:(await SecureStore.getItemAsync(SECURE_KEY_NAME))||'',status:'READ_OK'};}catch(e){return{ok:false,value:'',status:'READ_FAILED',error:e?.message||'Secure key storage could not be read.'};}}
export async function getApiKey(){return(await getApiKeyResult()).value;}
export function setApiKey(value){const op=async()=>{try{if(value)await SecureStore.setItemAsync(SECURE_KEY_NAME,value);else await SecureStore.deleteItemAsync(SECURE_KEY_NAME);return{ok:true,persisted:true,status:'SAVED_SECURELY'};}catch(e){return{ok:false,persisted:false,status:'SESSION_ONLY',error:e?.message||'Secure key persistence is unavailable.'};}}; secureWriteChain=secureWriteChain.then(op,op); return secureWriteChain;}

export async function getTogetherApiKeyResult(){try{return{ok:true,value:(await SecureStore.getItemAsync(SECURE_TOGETHER_KEY_NAME))||'',status:'READ_OK'};}catch(e){return{ok:false,value:'',status:'READ_FAILED',error:e?.message||'Together AI secure key storage could not be read.'};}}
export async function getTogetherApiKey(){return(await getTogetherApiKeyResult()).value;}
export function setTogetherApiKey(value){const op=async()=>{try{if(value)await SecureStore.setItemAsync(SECURE_TOGETHER_KEY_NAME,value);else await SecureStore.deleteItemAsync(SECURE_TOGETHER_KEY_NAME);return{ok:true,persisted:true,status:'SAVED_SECURELY'};}catch(e){return{ok:false,persisted:false,status:'SESSION_ONLY',error:e?.message||'Together AI secure key persistence is unavailable.'};}}; secureWriteChain=secureWriteChain.then(op,op); return secureWriteChain;}
export async function getLLMSettingsPin(){try{return(await SecureStore.getItemAsync(SECURE_LLM_SETTINGS_PIN))||'';}catch(_){throw new Error('Secure PIN storage could not be read on this device.');}}
export async function setLLMSettingsPin(value){try{if(value)await SecureStore.setItemAsync(SECURE_LLM_SETTINGS_PIN,await createPinVerifierAsync(value));else await SecureStore.deleteItemAsync(SECURE_LLM_SETTINGS_PIN);return{ok:true};}catch(_){throw new Error('Secure PIN storage is unavailable on this device.');}}

export async function getJSONResult(key,fallback){try{const raw=await AsyncStorage.getItem(key);if(raw==null)return{ok:true,status:'MISSING',value:fallback};try{return{ok:true,status:'FOUND',value:JSON.parse(raw)};}catch(e){return{ok:false,status:'CORRUPT',value:fallback,error:e?.message||'Stored JSON is corrupt.'};}}catch(e){return{ok:false,status:'READ_FAILED',value:fallback,error:e?.message||'Storage read failed.'};}}
export async function getJSON(key,fallback){return(await getJSONResult(key,fallback)).value;}
export async function setJSON(key,value){try{await AsyncStorage.setItem(key,JSON.stringify(value));return{ok:true,status:'SAVED'};}catch(e){return{ok:false,status:'SAVE_FAILED',error:e?.message||'Storage write failed.'};}}
async function readVersionedRaw(key){try{const raw=await AsyncStorage.getItem(key);if(raw==null)return{ok:true,status:'MISSING',raw:null,state:null};try{return{ok:true,status:'FOUND',raw,state:normaliseCState(JSON.parse(raw))};}catch(e){return{ok:false,status:'CORRUPT',raw,state:null,error:e?.message||'Versioned state is corrupt.'};}}catch(e){return{ok:false,status:'READ_FAILED',raw:null,state:null,error:e?.message||'Versioned state could not be read.'};}}
export async function getVersionedAppStateResult(){const primary=await readVersionedRaw(VERSIONED_APP_STATE_KEY);if(primary.ok)return primary;const backup=await readVersionedRaw(VERSIONED_APP_STATE_BACKUP_KEY);return{...primary,backupStatus:backup.status,backupState:backup.ok&&backup.state?backup.state:null,recoverable:Boolean(backup.ok&&backup.state)};}
export async function getVersionedAppState(fallback){const r=await getVersionedAppStateResult();if(r.ok)return r.state??fallback;throw new Error(r.recoverable?'Primary state is damaged; verified previous state is available for explicit recovery.':r.error||'Versioned state read failed.');}
export function setVersionedAppState(state){const intended=serialiseExact(state);const op=async()=>{try{const previous=await AsyncStorage.getItem(VERSIONED_APP_STATE_KEY);const writes=[[VERSIONED_APP_STATE_KEY,intended]];if(previous&&previous!==intended)writes.unshift([VERSIONED_APP_STATE_BACKUP_KEY,previous]);await AsyncStorage.multiSet(writes);return{ok:true,status:'SAVED',serialised:intended};}catch(e){return{ok:false,status:'SAVE_FAILED',error:e?.message||'State write failed.'};}};stateWriteChain=stateWriteChain.then(op,op);return stateWriteChain;}
export function verifyVersionedAppState(expected,actual){try{return serialiseExact(expected)===serialiseExact(actual);}catch(_){return false;}}
export async function persistAndVerifyVersionedAppState(state){const intended=serialiseExact(state);const written=await setVersionedAppState(state);if(!written.ok)return{ok:false,persisted:false,status:'SAVE_FAILED',error:written.error||'State write failed.'};const actualRaw=await readVersionedRaw(VERSIONED_APP_STATE_KEY);if(!actualRaw.ok||actualRaw.raw==null)return{ok:false,persisted:false,status:'SAVE_FAILED',error:'Durable state read-back failed.'};const ok=actualRaw.raw===intended;if(!ok)return{ok:false,persisted:false,status:'SAVE_FAILED',error:'Durable state differs from the exact intended schema.'};return{ok:true,persisted:true,status:'SAVED',state:actualRaw.state,serialised:intended};}
export async function restoreVersionedBackup(){const r=await getVersionedAppStateResult();if(!r.backupState) return{ok:false,status:'NO_BACKUP',error:'No verified previous state is available.'};return persistAndVerifyVersionedAppState(r.backupState);}
export async function commitStateTransaction(previousState,candidateState){const candidate=await persistAndVerifyVersionedAppState(candidateState);if(candidate.ok)return{...candidate,committed:true};const rollback=await persistAndVerifyVersionedAppState(previousState);return{ok:false,committed:false,status:'ROLLED_BACK',error:candidate.error||'Transaction failed.',rollbackOk:rollback.ok,state:rollback.ok?rollback.state:previousState};}
export const INITIAL_MODELS={OpenRouter:[{id:'openrouter/auto',name:'OpenRouter Auto'}]};
export const DEFAULT_SYSTEM_PROMPT='You are a helpful, accurate, and highly capable AI assistant. Provide concise, clear, structured responses grounded in the information available.';
export function formatProviderName(prefix){const map={openai:'OpenAI',anthropic:'Anthropic','meta-llama':'Meta (Llama)',google:'Google',mistralai:'Mistral AI',cohere:'Cohere'};return map[prefix.toLowerCase()]||prefix.charAt(0).toUpperCase()+prefix.slice(1);}
