import fs from 'node:fs';import path from 'node:path';
const root=process.cwd(), read=(f)=>fs.readFileSync(path.join(root,f),'utf8'), json=(f)=>JSON.parse(read(f)), assert=(c,m)=>{if(!c)throw new Error(m)};
const readIf=(f)=>{try{return read(f)}catch{return ''}};
const pkg=json('package.json'),lock=json('package-lock.json'),app=json('app.json'),source=read('App.js'),styles=read('src/styles.js'),privacyText=read('PRIVACY.md');
assert(fs.existsSync(path.join(root,'tests/codeDumpIntegrity.test.mjs')),'code-dump integrity regression tests missing');


const workflow=readIf('.github/workflows/android-apk.yml') || readIf('../.github/workflows/android-apk.yml'),readme=read('README.md'),workspace=read('src/workspaces/workspaceSchema.mjs'),backup=read('src/backup/backupService.mjs'),storage=read('src/utils/storage.js'),project=read('src/export/projectArchive.mjs'),docProject=read('src/documents/documentProjectArchive.mjs'),docStudio=read('src/components/DocumentStudio.js'),docTarget=read('src/components/DocumentTargetSheet.js'),protectedTools=read('src/components/ProtectedWorkspaceTools.js'),bubble=read('src/components/MessageBubble.js'),messageActions=read('src/components/MessageActionSheet.js'),primitives=read('src/ui/primitives.js'),responsive=read('src/ui/responsive.mjs'),settings=read('src/components/SettingsSheet.js'),protectedSettings=read('src/components/LLMSettingsSheet.js'),appLock=read('src/security/appLock.mjs'),deviceLock=read('src/components/DeviceLockScreen.js'),outputTokens=read('src/utils/outputTokens.mjs'),archivePolicy=read('src/utils/archivePolicy.mjs');
assert(pkg.version==='1.5.4'&&lock.version==='1.5.4'&&lock.packages[''].version==='1.5.4','v1.5.4 package identity drift');
assert(app.expo.version==='1.5.4'&&app.expo.android.versionCode===22&&app.expo.android.package==='com.nexarenew.aiconsole','Expo/Android release identity drift');
assert(app.expo.orientation==='default'&&app.expo.android.softwareKeyboardLayoutMode==='resize','adaptive orientation/IME contract missing');
assert(app.expo.userInterfaceStyle==='light'&&app.expo.backgroundColor==='#f8fafc','light-only app appearance contract missing');
assert(fs.existsSync(path.join(root,'.htaccess')),'.htaccess missing');
assert(readme.includes('AI Console v1.5.4')&&readme.includes('Document Studio Pro'),'README identity stale');
assert(workspace.includes('STORAGE_SCHEMA_VERSION_C = 6')&&workspace.includes('documentRevisions')&&workspace.includes('activeDocumentId')&&workspace.includes('usageLedger')&&workspace.includes('scheduledTasks'),'schema v6 merged intelligence state missing');
assert(storage.includes('SAVED_SECURELY')&&storage.includes('SESSION_ONLY')&&storage.includes('getApiKeyResult')&&storage.includes('READ_FAILED')&&storage.includes('persistAndVerifyVersionedAppState')&&storage.includes('SECURE_WRITE_OPTIONS')&&storage.includes('normaliseProviderApiKey'),'SecureStore/durable state result contract missing');
assert(pkg.dependencies?.['expo-local-authentication']==='~57.0.2'&&app.expo.plugins?.some((entry)=>Array.isArray(entry)&&entry[0]==='expo-local-authentication'),'Expo local-authentication native dependency/configuration missing');
assert(pkg.dependencies?.['expo-audio']==='~57.0.4'&&pkg.dependencies?.['expo-asset']==='~57.0.16'&&pkg.dependencies?.['@react-native-picker/picker']==='2.11.4'&&app.expo.plugins?.some((entry)=>(Array.isArray(entry)?entry[0]:entry)==='expo-audio')&&app.expo.plugins?.some((entry)=>(Array.isArray(entry)?entry[0]:entry)==='expo-asset'),'Together Sonic playback/voice-picker native dependencies or configuration missing');
assert(outputTokens.includes('MAX_OUTPUT_TOKENS = 1048576')&&outputTokens.includes('tokens >= 1000000'),'million-scale output-token control missing');
assert(archivePolicy.includes('maxFiles: 100')&&read('src/utils/rawZipPreflight.mjs').includes('maxEntries:100'),'100-entry ZIP import policy missing');
assert(appLock.includes('APP_LOCK_TIMEOUT_MS = 6 * 60 * 60 * 1000')&&appLock.includes('isAppLockDue')&&appLock.includes('disableAppLock'),'six-hour optional device-lock policy missing');
assert(deviceLock.includes('Unlock with your device')&&deviceLock.includes('This app relocks after six hours')&&!deviceLock.includes('TextInput'),'device-lock screen must be PIN-free');
assert(source.includes('LocalAuthentication.authenticateAsync')&&source.includes('disableDeviceFallback: false')&&source.includes('<DeviceLockScreen')&&source.includes('getAppLockSettings')&&source.includes('setAppLockSettings'),'device authentication/lock state is not wired into app startup');
assert(backup.includes('commitPreparedRestore')&&backup.includes('Rollback read-back verification failed'),'transactional restore verification missing');
assert(project.includes('rawZipPreflight')&&project.includes("import('jszip')")&&project.includes('documentRevisions')&&project.includes('PROJECT_ARCHIVE_SCHEMA_VERSION = 3')&&project.includes('IMPORTED_PAUSED'),'workspace archive v3/intelligence contract missing');

const intelligence=read('src/components/IntelligenceHub.js'),streamChat=read('src/utils/streamChat.js'),memory=read('src/memory/workspaceMemory.mjs'),skills=read('src/skills/skillEngine.mjs'),usage=read('src/usage/usageLedger.mjs'),tasks=read('src/tasks/taskScheduler.mjs'),fullVoice=read('src/voice/fullVoiceMode.mjs'),retryPolicy=read('src/providers/retryPolicy.mjs'),generationState=read('src/domain/generationState.mjs'),generationManager=read('src/services/generationManager.mjs'),conversationSchema=read('src/domain/conversationSchema.mjs'),privacy=read('src/utils/privacy.mjs');
const providerRegistry=read('src/providers/providerRegistry.mjs');
assert(providerRegistry.includes("OPENROUTER: 'openrouter'")&&providerRegistry.includes("TOGETHER: 'together'")&&providerRegistry.includes('https://api.together.ai/v1/chat/completions')&&providerRegistry.includes('https://api.together.ai/v1/models')&&providerRegistry.includes('https://api.together.ai/v1/audio/speech')&&providerRegistry.includes('https://api.together.ai/v1/voices')&&providerRegistry.includes("TOGETHER_SONIC_TTS_MODEL = 'cartesia/sonic-3'"),'dual-provider/Together Sonic registry contract missing');
assert(storage.includes('togetherApiKey')&&storage.includes('getTogetherApiKeyResult')&&storage.includes('setTogetherApiKey'),'Together SecureStore contract missing');
assert(intelligence.includes('Memory')&&intelligence.includes('Skills')&&intelligence.includes('Tasks')&&intelligence.includes('Usage')&&intelligence.includes('Cost guardrails'),'intelligence settings hub missing authorised controls');
assert(streamChat.includes('TOGETHER')&&streamChat.includes('togetherApiKey')&&streamChat.includes('TOGETHER_API_BASE_URL'),'Together chat provider path missing');
assert(memory.includes('deriveAutomaticMemory')&&memory.includes('remember')&&memory.includes('forget'),'automatic memory engine missing');
assert(skills.includes('DEFAULT_SKILLS')&&skills.includes('applySkillsToPrompt'),'skills engine missing');
assert(usage.includes('recordUsage')&&usage.includes('enforceUsageGuardrails'),'usage/cost guardrails missing');
assert(tasks.includes('createScheduledTask')&&tasks.includes('listDueScheduledTasks'),'scheduled AI tasks missing');
assert(fullVoice.includes('FULL_VOICE_MODE'),'full voice mode missing');
assert(retryPolicy.includes('Retry-After')&&retryPolicy.includes('exponential'),'provider retry/backoff policy missing');
assert(generationState.includes('GENERATING')&&generationState.includes('CANCELLED'),'generation state model missing');
assert(generationManager.includes('AbortController')&&generationManager.includes('cancel'),'generation manager cancellation missing');
assert(conversationSchema.includes('CONVERSATION_SCHEMA_VERSION'),'conversation schema/versioning missing');
assert(privacy.includes('redact'),'privacy/redaction utility missing');
assert(bubble.includes('Copy')&&bubble.includes('Regenerate')&&bubble.includes('Download'),'message bubble actions missing');
assert(messageActions.includes('copy')||messageActions.includes('Copy'),'message action sheet copy missing');
assert(primitives.includes('minHeight: 48')||settings.includes('minHeight: 48'),'48px touch-target contract missing');
assert(responsive.includes('isWide')||responsive.includes('wide'),'responsive/wide layout contract missing');
assert(protectedSettings.includes('authenticate')||protectedSettings.includes('LocalAuthentication'),'protected settings device-auth contract missing');
assert(protectedTools.length>0,'protected workspace tools missing');
assert(docStudio.includes('Document')&&docTarget.includes('target'),'document studio/target workflow missing');
assert(docProject.includes('document'),'document project archive missing');
assert(privacyText.length>0,'privacy documentation missing');
console.log('STATIC_CHECK: PASS');
