export const DOCUMENT_TEMPLATES=Object.freeze([
 {id:'blank',name:'Blank',category:'General',documentType:'GENERAL',title:'Untitled Document',defaultComposition:{pageSize:'A4',orientation:'portrait',margins:{top:20,right:20,bottom:20,left:20}},placeholders:[],sections:[{type:'PARAGRAPH',content:''}]},
 {id:'general-report',name:'General Report',category:'Reports',documentType:'REPORT',title:'General Report',defaultComposition:{pageSize:'A4',orientation:'portrait',margins:{top:20,right:20,bottom:20,left:20},coverPage:true,pageNumbers:true,tableOfContents:true},placeholders:['author','date'],sections:[{type:'HEADING',content:'Executive Summary',headingLevel:1},{type:'PARAGRAPH',content:''},{type:'HEADING',content:'Findings',headingLevel:1},{type:'PARAGRAPH',content:''},{type:'HEADING',content:'Recommendations',headingLevel:1},{type:'PARAGRAPH',content:''}]},
 {id:'technical-spec',name:'Technical Specification',category:'Technical',documentType:'SPECIFICATION',title:'Technical Specification',defaultComposition:{pageSize:'A4',orientation:'portrait',margins:{top:20,right:20,bottom:20,left:20},coverPage:true,tableOfContents:true,pageNumbers:true},placeholders:['systemName','owner','version'],sections:[{type:'HEADING',content:'Scope',headingLevel:1},{type:'PARAGRAPH',content:''},{type:'HEADING',content:'Requirements',headingLevel:1},{type:'PARAGRAPH',content:''},{type:'HEADING',content:'Architecture',headingLevel:1},{type:'PARAGRAPH',content:''},{type:'HEADING',content:'Verification',headingLevel:1},{type:'PARAGRAPH',content:''}]},
 {id:'audit-report',name:'Audit Report',category:'Reports',documentType:'AUDIT',title:'Audit Report',defaultComposition:{pageSize:'A4',orientation:'portrait',margins:{top:20,right:20,bottom:20,left:20},coverPage:true,tableOfContents:true,pageNumbers:true},placeholders:['auditSubject','auditor','date'],sections:[{type:'HEADING',content:'Executive Summary',headingLevel:1},{type:'PARAGRAPH',content:''},{type:'HEADING',content:'Scope and Method',headingLevel:1},{type:'PARAGRAPH',content:''},{type:'HEADING',content:'Findings',headingLevel:1},{type:'PARAGRAPH',content:''},{type:'HEADING',content:'Risk and Severity',headingLevel:1},{type:'PARAGRAPH',content:''},{type:'HEADING',content:'Remediation and Acceptance Criteria',headingLevel:1},{type:'PARAGRAPH',content:''}]},
 {id:'implementation-plan',name:'Implementation Plan',category:'Planning',documentType:'PLAN',title:'Implementation Plan',defaultComposition:{pageSize:'A4',orientation:'portrait',margins:{top:20,right:20,bottom:20,left:20},coverPage:true,tableOfContents:true,pageNumbers:true},placeholders:['projectName','owner','targetDate'],sections:[{type:'HEADING',content:'Objective',headingLevel:1},{type:'PARAGRAPH',content:''},{type:'HEADING',content:'Scope',headingLevel:1},{type:'PARAGRAPH',content:''},{type:'HEADING',content:'Workstreams and Tasks',headingLevel:1},{type:'PARAGRAPH',content:''},{type:'HEADING',content:'Dependencies and Risks',headingLevel:1},{type:'PARAGRAPH',content:''},{type:'HEADING',content:'Verification and Completion Criteria',headingLevel:1},{type:'PARAGRAPH',content:''}]},
 {id:'memorandum',name:'Memorandum',category:'Business',documentType:'MEMORANDUM',title:'Memorandum',defaultComposition:{pageSize:'A4',orientation:'portrait',margins:{top:22,right:22,bottom:22,left:22},pageNumbers:true},placeholders:['to','from','date','subject'],sections:[{type:'HEADING',content:'Purpose',headingLevel:1},{type:'PARAGRAPH',content:''},{type:'HEADING',content:'Background',headingLevel:1},{type:'PARAGRAPH',content:''},{type:'HEADING',content:'Analysis',headingLevel:1},{type:'PARAGRAPH',content:''},{type:'HEADING',content:'Recommendation',headingLevel:1},{type:'PARAGRAPH',content:''}]},
 {id:'proposal',name:'Proposal',category:'Business',documentType:'PROPOSAL',title:'Proposal',defaultComposition:{pageSize:'A4',orientation:'portrait',margins:{top:20,right:20,bottom:20,left:20},coverPage:true,tableOfContents:true,pageNumbers:true},placeholders:['proposalTitle','preparedFor','preparedBy','date'],sections:[{type:'HEADING',content:'Executive Summary',headingLevel:1},{type:'PARAGRAPH',content:''},{type:'HEADING',content:'Problem / Opportunity',headingLevel:1},{type:'PARAGRAPH',content:''},{type:'HEADING',content:'Proposed Approach',headingLevel:1},{type:'PARAGRAPH',content:''},{type:'HEADING',content:'Deliverables and Timeline',headingLevel:1},{type:'PARAGRAPH',content:''},{type:'HEADING',content:'Acceptance Criteria',headingLevel:1},{type:'PARAGRAPH',content:''}]},
 {id:'formal-letter',name:'Formal Letter',category:'Correspondence',documentType:'LETTER',title:'Formal Letter',defaultComposition:{pageSize:'A4',orientation:'portrait',margins:{top:24,right:24,bottom:24,left:24}},placeholders:['sender','recipient','date','subject'],sections:[{type:'PARAGRAPH',content:'Dear [Recipient],'}, {type:'PARAGRAPH',content:''},{type:'PARAGRAPH',content:'Yours faithfully,'},{type:'PARAGRAPH',content:'[Sender]'}]},
 {id:'meeting-notes',name:'Meeting Notes',category:'Notes',documentType:'NOTES',title:'Meeting Notes',defaultComposition:{pageSize:'A4',orientation:'portrait',margins:{top:18,right:18,bottom:18,left:18}},placeholders:['meetingTitle','date','attendees'],sections:[{type:'HEADING',content:'Attendees',headingLevel:1},{type:'LIST',content:''},{type:'HEADING',content:'Discussion',headingLevel:1},{type:'PARAGRAPH',content:''},{type:'HEADING',content:'Actions',headingLevel:1},{type:'LIST',content:''}]}
]);
export const getDocumentTemplate=id=>DOCUMENT_TEMPLATES.find(t=>t.id===id)||DOCUMENT_TEMPLATES[0];
