import * as FileSystem from 'expo-file-system/legacy';
import pako from 'pako';
import { PDF_LIMITS } from './pdfPipeline.mjs';
import { extractPdfPagesFromBytes, inspectPdfBytes } from './pdfTextExtract.mjs';
const MAX_INFLATED_STREAM_BYTES=4*1024*1024;
const base64ToBytes=(base64)=>{const binary=globalThis.atob(String(base64||''));return Uint8Array.from(binary,c=>c.charCodeAt(0));};
const loadBytes=async(file)=>{if(!file?.uri)throw new Error('PDF file is no longer available to the active attachment session.');let size=Number(file.size)||0;try{const info=await FileSystem.getInfoAsync(file.uri,{size:true});size=Number(info?.size)||size;}catch(_){}if(!size)throw new Error('Unable to establish PDF source size safely.');if(size>PDF_LIMITS.maxBytes)throw new Error('PDF exceeds configured size ceiling before allocation.');const base64=await FileSystem.readAsStringAsync(file.uri,{encoding:FileSystem.EncodingType.Base64});const bytes=base64ToBytes(base64);if(bytes.length>PDF_LIMITS.maxBytes)throw new Error('PDF source exceeds configured size ceiling.');return bytes;};
const boundedInflate=(bytes)=>{const inflator=new pako.Inflate({chunkSize:16384});const chunks=[];let total=0;inflator.onData=(chunk)=>{total+=chunk.length;if(total>MAX_INFLATED_STREAM_BYTES)throw new Error('PDF compressed stream expands beyond the allowed limit.');chunks.push(Uint8Array.from(chunk));};inflator.push(bytes,true);if(inflator.err)throw new Error(inflator.msg||'PDF compressed stream decoding failed.');const out=new Uint8Array(total);let offset=0;for(const chunk of chunks){out.set(chunk,offset);offset+=chunk.length;}return out;};
export const localPdfAdapter={async inspect(file){const bytes=await loadBytes(file);const i=inspectPdfBytes(bytes);return{encrypted:i.encrypted,pageCount:i.pageCount};},async extractPages(file,selectedPages,onPage=()=>{}){const bytes=await loadBytes(file);const pages=extractPdfPagesFromBytes(bytes,selectedPages,{inflate:boundedInflate});pages.forEach((page,index)=>onPage({...page,progress:Math.round(((index+1)/Math.max(1,pages.length))*100)}));return pages;}};
