export const VoiceStatus = Object.freeze({ IDLE: 'IDLE', REQUESTING_PERMISSION: 'REQUESTING_PERMISSION', READY: 'READY', CAPTURING: 'CAPTURING', REVIEWING: 'REVIEWING', PLAYING: 'PLAYING', PAUSED: 'PAUSED', FAILED: 'FAILED', UNAVAILABLE: 'UNAVAILABLE' });
const allowed = { IDLE: ['REQUESTING_PERMISSION', 'UNAVAILABLE'], REQUESTING_PERMISSION: ['READY', 'FAILED'], READY: ['CAPTURING', 'PLAYING', 'IDLE'], CAPTURING: ['REVIEWING', 'READY', 'FAILED'], REVIEWING: ['CAPTURING', 'READY'], PLAYING: ['PAUSED', 'READY', 'FAILED'], PAUSED: ['PLAYING', 'READY'], FAILED: ['REQUESTING_PERMISSION', 'READY'], UNAVAILABLE: [] };
export const createVoiceState = (now = Date.now()) => ({ status: VoiceStatus.IDLE, locale: 'en-GB', continuous: false, interimTranscript: '', finalTranscript: '', playbackSpeed: 1, error: null, updatedAt: now });
export const transitionVoice = (state, status, patch = {}, now = Date.now()) => { if (!allowed[state?.status]?.includes(status)) throw new Error(`Invalid voice transition: ${state?.status || 'MISSING'} → ${status}`); return { ...state, ...patch, status, error: status === VoiceStatus.FAILED ? String(patch.error || 'Voice operation failed.') : null, updatedAt: now }; };
export const setVoiceLocale = (state, locale, now = Date.now()) => ({ ...state, locale: typeof locale === 'string' && locale.trim() ? locale : 'en-GB', updatedAt: now });
export const setInterimTranscript = (state, interimTranscript, now = Date.now()) => ({ ...state, interimTranscript: String(interimTranscript || ''), updatedAt: now });
export const reviewFinalTranscript = (state, finalTranscript, now = Date.now()) => transitionVoice({ ...state, finalTranscript: String(finalTranscript || '') }, VoiceStatus.REVIEWING, {}, now);
export const clearVoiceTranscript = (state, now = Date.now()) => ({ ...state, interimTranscript: '', finalTranscript: '', updatedAt: now });
export const handleVoiceInterruption = (state, now = Date.now()) => state.status === VoiceStatus.CAPTURING || state.status === VoiceStatus.PLAYING ? { ...state, status: VoiceStatus.READY, error: 'Voice operation interrupted by device audio lifecycle.', updatedAt: now } : state;
